In [ ]:
# Import the python script (dropping the .py extension)
import epo_api_codes

# Define your EPO OPS API credentials
CONSUMER_KEY = "put_key"
CONSUMER_SECRET = "put_secret"

# (Optional) Check your weekly data quota before running
print("Checking quota...")
epo_api_codes.check_epo_quota(CONSUMER_KEY, CONSUMER_SECRET)

# Run the extraction for the year 2022 to 2025
print("\nStarting extraction...")
df_2022_2025_applicant = epo_api_codes.download_patent_ids(
    consumer_key=CONSUMER_KEY,
    consumer_secret=CONSUMER_SECRET,
    start_year=2022,
    end_year=2025,
    applicant_filter = "Alnylam*",  # Wildcard company name to narrow results.
                                    # e.g. "Alnylam*" → only Alnylam patents
                                    #      None       → all applicants (no filter)

    only_applicant   = True,   # Controls what the query is built from:
                                # False → CPC/IPC codes + applicant filter (default)
                                # True  → applicant name only, codes are ignored
                                #         (use this for a full company portfolio)
)

# Display the first few rows of the extracted DataFrame
print(df_2022_2025_applicant.head()) # Wrapped in print() to ensure it displays in the console

Checking quota...
=============================================
      EPO OPS API - STATUS DASHBOARD
=============================================

[DATA CONSUMPTION]
Weekly Volume Used: 4.4886% (179.54 MB / 4000 MB)
Quota Remaining:    95.5114%
Current API Load:   30 requests/minute

---------------------------------------------
[OK] Server clear. Safe to proceed with extraction.
---------------------------------------------

Starting extraction...

=== STARTING EPO ID EXTRACTION (2022 - 2025) ===
[INFO] 1 independent query conditions.
[INFO] Applicant filter: Alnylam* (Only Applicant: True)

[INFO] Processing year 2022...
  -> Query 1/1: ...

[AUTH] Generating a new EPO access token...
[INFO] Year 2022: 153 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 153
[INFO] Requested: 91-153 | Received: 91-153 | Total expected: 153
[INFO] Raw records accumulated (including cross-query duplicates): 153
[INFO] After family deduplication: 153 unique IDs
[INFO] Records filtered (cross-query duplicates + prior-year skips): 0
[INFO] Families tracked globally so far: 153
  [AUTOSAVE] Year 2022: 153 IDs saved to EPO_IDs_AutoSave_2022.csv

[INFO] Processing year 2023...
  -> Query 1/1: ...
[INFO] Year 2023: 182 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 182
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 182
[INFO] Requested: 181-182 | Received: 181-182 | Total expected: 182
[INFO] Raw records accumulated (including cross-query duplicates): 182
[INFO] After family deduplication: 136 unique IDs
[INFO] Records filtered (cross-query duplicates + prior-year skips): 46
[INFO] Families tracked globally so far: 248
  [AUTOSAVE] Year 2023: 136 IDs saved to EPO_IDs_AutoSave_2023.csv

[INFO] Processing year 2024...
  -> Query 1/1: ...
[INFO] Year 2024: 171 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 171
[INFO] Requested: 91-171 | Received: 91-171 | Total expected: 171
[INFO] Raw records accumulated (including cross-query duplicates): 171
[INFO] After family deduplication: 109 unique IDs
[INFO] Records filtered (cross-query duplicates + prior-year skips): 62
[INFO] Families tracked globally so far: 290
  [AUTOSAVE] Year 2024: 109 IDs saved to EPO_IDs_AutoSave_2024.csv

[INFO] Processing year 2025...
  -> Query 1/1: ...
[INFO] Year 2025: 128 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 128
[INFO] Requested: 91-128 | Received: 91-128 | Total expected: 128
[INFO] Raw records accumulated (including cross-query duplicates): 128
[INFO] After family deduplication: 65 unique IDs
[INFO] Records filtered (cross-query duplicates + prior-year skips): 63
[INFO] Families tracked globally so far: 317
  [AUTOSAVE] Year 2025: 65 IDs saved to EPO_IDs_AutoSave_2025.csv

[SUCCESS] 317 unique patent families saved to: EPO_siRNA_IDs_2022_2025_only_applicant_Alnylam.csv
[TIME] Extraction completed in 1m 42s
          Patent_ID Family_ID Country
462  US2025376682A1  42062316      US
461  US2025346906A1  44761389      US
460  US2025034566A1  48326393      US
458  US2025075208A1  51230239      US
457  US2025188475A1  52573741      US

In [ ]:
# Import the python script (dropping the .py extension)
import epo_api_terms

# (Optional) Check your weekly data quota before running
print("Checking quota...")
epo_api_terms.check_epo_quota(CONSUMER_KEY, CONSUMER_SECRET)

# Run the extraction for the year 2022
print("\nStarting extraction...")
df_2022_2025_terms = epo_api_terms.download_patent_ids(
    consumer_key=CONSUMER_KEY,
    consumer_secret=CONSUMER_SECRET,
    start_year=2022,
    end_year=2025,
    applicant_filter=None # Change this if you want to filter by a specific applicant
)

# Display the first few rows of the extracted DataFrame
df_2022_2025_terms.head()

Checking quota...
=============================================
      EPO OPS API - STATUS DASHBOARD
=============================================

[DATA CONSUMPTION]
Weekly Volume Used: 4.4279% (177.11 MB / 4000 MB)
Quota Remaining:    95.5721%
Current API Load:   30 requests/minute

---------------------------------------------
[OK] Server clear. Safe to proceed with extraction.
---------------------------------------------

Starting extraction...

=== STARTING EPO ID EXTRACTION (2022 - 2025) ===
[INFO] 27 independent query conditions.
[INFO] Exclusions active: C12N15/115 (Aptamers), C12N15/117 (Immunomodulatory)

[INFO] Processing year 2022...
  -> Query 1/27: (ta=siRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...

[AUTH] Generating a new EPO access token...
[INFO] Year 2022: 450 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 450
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 450
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 450
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 450
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 450
  -> Query 2/27: (ta=RNAi* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 286 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 286
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 286
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 286
[INFO] Requested: 271-286 | Received: 271-286 | Total expected: 286
  -> Query 3/27: (ta=dsRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 187 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 187
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 187
[INFO] Requested: 181-187 | Received: 181-187 | Total expected: 187
  -> Query 4/27: (ta=iRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 87 results. Fetching yearly...
[INFO] Requested: 1-87 | Received: 1-87 | Total expected: 87
  -> Query 5/27: (ta=dsRNAi* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 18 results. Fetching yearly...
[INFO] Requested: 1-18 | Received: 1-18 | Total expected: 18
  -> Query 6/27: (ta=oligonucleotide* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 1428 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1428
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1428
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1428
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1428
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1428
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1428
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1428
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1428
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1428
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1428
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1428
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1428
[INFO] Requested: 1081-1170 | Received: 1081-1170 | Total expected: 1428
[INFO] Requested: 1171-1260 | Received: 1171-1260 | Total expected: 1428
[INFO] Requested: 1261-1350 | Received: 1261-1350 | Total expected: 1428
[INFO] Requested: 1351-1428 | Received: 1351-1428 | Total expected: 1428
  -> Query 7/27: (ta="si-RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 3 results. Fetching yearly...
[INFO] Requested: 1-3 | Received: 1-3 | Total expected: 3
  -> Query 8/27: (ta="ds RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 1 results. Fetching yearly...
[INFO] Requested: 1-1 | Received: 1-1 | Total expected: 1
  -> Query 9/27: (ta="RNA interference" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 133 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 133
[INFO] Requested: 91-133 | Received: 91-133 | Total expected: 133
  -> Query 10/27: (ta="interfering RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 99 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 99
[INFO] Requested: 91-99 | Received: 91-99 | Total expected: 99
  -> Query 11/27: (ta="small interfering RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 54 results. Fetching yearly...
[INFO] Requested: 1-54 | Received: 1-54 | Total expected: 54
  -> Query 12/27: (ta="small interfering RNAs" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 5 results. Fetching yearly...
[INFO] Requested: 1-5 | Received: 1-5 | Total expected: 5
  -> Query 13/27: (ta="short interfering RNAs" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 1 results. Fetching yearly...
[INFO] Requested: 1-1 | Received: 1-1 | Total expected: 1
  -> Query 14/27: (ta="short interfering RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 11 results. Fetching yearly...
[INFO] Requested: 1-11 | Received: 1-11 | Total expected: 11
  -> Query 15/27: (ta="double stranded RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 102 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 102
[INFO] Requested: 91-102 | Received: 91-102 | Total expected: 102
  -> Query 16/27: (ta="double stranded RNAs" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 8 results. Fetching yearly...
[INFO] Requested: 1-8 | Received: 1-8 | Total expected: 8
  -> Query 17/27: (ta="RNA duplex" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 4 results. Fetching yearly...
[INFO] Requested: 1-4 | Received: 1-4 | Total expected: 4
  -> Query 18/27: (ta="RNA duplexes" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 1 results. Fetching yearly...
[INFO] Requested: 1-1 | Received: 1-1 | Total expected: 1
  -> Query 19/27: (ta="small interfering ribonucleic acid" NOT (cpc="C12N15/115" OR cpc="C12N15/11...
[INFO] Year 2022: 35 results. Fetching yearly...
[INFO] Requested: 1-35 | Received: 1-35 | Total expected: 35
  -> Query 20/27: (ta="small interfering ribonucleic acids" NOT (cpc="C12N15/115" OR cpc="C12N15/1...
[INFO] Year 2022: 2 results. Fetching yearly...
[INFO] Requested: 1-2 | Received: 1-2 | Total expected: 2
  -> Query 21/27: (ta="short interfering ribonucleic acid" NOT (cpc="C12N15/115" OR cpc="C12N15/11...
[WARNING 404] Slice not found (attempt 1/4). Retrying...
[WARNING 404] Slice not found (attempt 2/4). Retrying...
[WARNING 404] Slice not found (attempt 3/4). Retrying...
  -> Query 22/27: (ta="short interfering ribonucleic acids" NOT (cpc="C12N15/115" OR cpc="C12N15/1...
[WARNING 404] Slice not found (attempt 1/4). Retrying...
[WARNING 404] Slice not found (attempt 2/4). Retrying...
[WARNING 404] Slice not found (attempt 3/4). Retrying...
  -> Query 23/27: (ta="double stranded ribonucleic acid" NOT (cpc="C12N15/115" OR cpc="C12N15/117"...
[INFO] Year 2022: 59 results. Fetching yearly...
[INFO] Requested: 1-59 | Received: 1-59 | Total expected: 59
  -> Query 24/27: (ta="double stranded ribonucleic acids" NOT (cpc="C12N15/115" OR cpc="C12N15/117...
[INFO] Year 2022: 1 results. Fetching yearly...
[INFO] Requested: 1-1 | Received: 1-1 | Total expected: 1
  -> Query 25/27: (ta="ribonucleic acid interference" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 16 results. Fetching yearly...
[INFO] Requested: 1-16 | Received: 1-16 | Total expected: 16
  -> Query 26/27: (ta="interfering ribonucleic acid" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 35 results. Fetching yearly...
[INFO] Requested: 1-35 | Received: 1-35 | Total expected: 35
  -> Query 27/27: (ta="interfering ribonucleic acids" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 2 results. Fetching yearly...
[INFO] Requested: 1-2 | Received: 1-2 | Total expected: 2
[INFO] Raw records accumulated (including cross-query duplicates): 3028
[INFO] After family deduplication: 2336 unique IDs
[INFO] Records filtered (cross-query duplicates + prior-year skips): 692
[INFO] Families tracked globally so far: 2336
  [AUTOSAVE] Year 2022: 2336 IDs saved to EPO_IDs_AutoSave_2022.csv

[INFO] Processing year 2023...
  -> Query 1/27: (ta=siRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 646 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 646
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 646
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 646
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 646
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 646
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 646
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 646
[INFO] Requested: 631-646 | Received: 631-646 | Total expected: 646
  -> Query 2/27: (ta=RNAi* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 385 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 385
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 385
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 385
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 385
[INFO] Requested: 361-385 | Received: 361-385 | Total expected: 385
  -> Query 3/27: (ta=dsRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 338 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 338
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 338

[AUTH] Generating a new EPO access token...
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 338
[INFO] Requested: 271-338 | Received: 271-338 | Total expected: 338
  -> Query 4/27: (ta=iRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 96 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 96
[INFO] Requested: 91-96 | Received: 91-96 | Total expected: 96
  -> Query 5/27: (ta=dsRNAi* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 24 results. Fetching yearly...
[INFO] Requested: 1-24 | Received: 1-24 | Total expected: 24
  -> Query 6/27: (ta=oligonucleotide* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 1577 results. Fetching yearly...
  -> Query 7/27: (ta="si-RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 2 results. Fetching yearly...
[INFO] Requested: 1-2 | Received: 1-2 | Total expected: 2
  -> Query 8/27: (ta="ds RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 1 results. Fetching yearly...
[INFO] Requested: 1-1 | Received: 1-1 | Total expected: 1
  -> Query 9/27: (ta="RNA interference" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 171 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 171
[INFO] Requested: 91-171 | Received: 91-171 | Total expected: 171
  -> Query 10/27: (ta="interfering RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 133 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 133
[INFO] Requested: 91-133 | Received: 91-133 | Total expected: 133
  -> Query 11/27: (ta="small interfering RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 79 results. Fetching yearly...
[INFO] Requested: 1-79 | Received: 1-79 | Total expected: 79
  -> Query 12/27: (ta="small interfering RNAs" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 8 results. Fetching yearly...
[INFO] Requested: 1-8 | Received: 1-8 | Total expected: 8
  -> Query 13/27: (ta="short interfering RNAs" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[WARNING 404] Slice not found (attempt 1/4). Retrying...
[WARNING 404] Slice not found (attempt 2/4). Retrying...
[WARNING 404] Slice not found (attempt 3/4). Retrying...
  -> Query 14/27: (ta="short interfering RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 11 results. Fetching yearly...
[INFO] Requested: 1-11 | Received: 1-11 | Total expected: 11
  -> Query 15/27: (ta="double stranded RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 128 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 128
[INFO] Requested: 91-128 | Received: 91-128 | Total expected: 128
  -> Query 16/27: (ta="double stranded RNAs" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 7 results. Fetching yearly...
[INFO] Requested: 1-7 | Received: 1-7 | Total expected: 7
  -> Query 17/27: (ta="RNA duplex" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 4 results. Fetching yearly...
[INFO] Requested: 1-4 | Received: 1-4 | Total expected: 4
  -> Query 18/27: (ta="RNA duplexes" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 1 results. Fetching yearly...
[INFO] Requested: 1-1 | Received: 1-1 | Total expected: 1
  -> Query 19/27: (ta="small interfering ribonucleic acid" NOT (cpc="C12N15/115" OR cpc="C12N15/11...
[INFO] Year 2023: 87 results. Fetching yearly...
[INFO] Requested: 1-87 | Received: 1-87 | Total expected: 87
  -> Query 20/27: (ta="small interfering ribonucleic acids" NOT (cpc="C12N15/115" OR cpc="C12N15/1...
[INFO] Year 2023: 3 results. Fetching yearly...
[INFO] Requested: 1-3 | Received: 1-3 | Total expected: 3
  -> Query 21/27: (ta="short interfering ribonucleic acid" NOT (cpc="C12N15/115" OR cpc="C12N15/11...
[WARNING 404] Slice not found (attempt 1/4). Retrying...
[WARNING 404] Slice not found (attempt 2/4). Retrying...
[WARNING 404] Slice not found (attempt 3/4). Retrying...
  -> Query 22/27: (ta="short interfering ribonucleic acids" NOT (cpc="C12N15/115" OR cpc="C12N15/1...
[INFO] Year 2023: 1 results. Fetching yearly...
[INFO] Requested: 1-1 | Received: 1-1 | Total expected: 1
  -> Query 23/27: (ta="double stranded ribonucleic acid" NOT (cpc="C12N15/115" OR cpc="C12N15/117"...
[INFO] Year 2023: 100 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 100
[INFO] Requested: 91-100 | Received: 91-100 | Total expected: 100
  -> Query 24/27: (ta="double stranded ribonucleic acids" NOT (cpc="C12N15/115" OR cpc="C12N15/117...
[WARNING 404] Slice not found (attempt 1/4). Retrying...
[WARNING 404] Slice not found (attempt 2/4). Retrying...
[WARNING 404] Slice not found (attempt 3/4). Retrying...
  -> Query 25/27: (ta="ribonucleic acid interference" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 43 results. Fetching yearly...
[INFO] Requested: 1-43 | Received: 1-43 | Total expected: 43
  -> Query 26/27: (ta="interfering ribonucleic acid" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 88 results. Fetching yearly...
[INFO] Requested: 1-88 | Received: 1-88 | Total expected: 88
  -> Query 27/27: (ta="interfering ribonucleic acids" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2023: 4 results. Fetching yearly...
[INFO] Requested: 1-4 | Received: 1-4 | Total expected: 4
[INFO] Raw records accumulated (including cross-query duplicates): 2360
[INFO] After family deduplication: 1317 unique IDs
[INFO] Records filtered (cross-query duplicates + prior-year skips): 1043
[INFO] Families tracked globally so far: 3498
  [AUTOSAVE] Year 2023: 1317 IDs saved to EPO_IDs_AutoSave_2023.csv

[INFO] Processing year 2024...
  -> Query 1/27: (ta=siRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 774 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 774
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 774
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 774
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 774
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 774
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 774
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 774
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 774
[INFO] Requested: 721-774 | Received: 721-774 | Total expected: 774
  -> Query 2/27: (ta=RNAi* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 419 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 419
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 419
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 419
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 419
[INFO] Requested: 361-419 | Received: 361-419 | Total expected: 419
  -> Query 3/27: (ta=dsRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 377 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 377
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 377
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 377
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 377
[INFO] Requested: 361-377 | Received: 361-377 | Total expected: 377
  -> Query 4/27: (ta=iRNA* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 106 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 106
[INFO] Requested: 91-106 | Received: 91-106 | Total expected: 106
  -> Query 5/27: (ta=dsRNAi* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 26 results. Fetching yearly...
[INFO] Requested: 1-26 | Received: 1-26 | Total expected: 26
  -> Query 6/27: (ta=oligonucleotide* NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 1856 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1856
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1856
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1856
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1856
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1856

[AUTH] Generating a new EPO access token...
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1856
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1856
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1856
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1856
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1856
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1856
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1856
[INFO] Requested: 1081-1170 | Received: 1081-1170 | Total expected: 1856
[INFO] Requested: 1171-1260 | Received: 1171-1260 | Total expected: 1856
[INFO] Requested: 1261-1350 | Received: 1261-1350 | Total expected: 1856
[INFO] Requested: 1351-1440 | Received: 1351-1440 | Total expected: 1856
[INFO] Requested: 1441-1530 | Received: 1441-1530 | Total expected: 1856
[INFO] Requested: 1531-1620 | Received: 1531-1620 | Total expected: 1856
[INFO] Requested: 1621-1710 | Received: 1621-1710 | Total expected: 1856
[INFO] Requested: 1711-1800 | Received: 1711-1800 | Total expected: 1856
[INFO] Requested: 1801-1856 | Received: 1801-1856 | Total expected: 1856
  -> Query 7/27: (ta="si-RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 4 results. Fetching yearly...
[INFO] Requested: 1-4 | Received: 1-4 | Total expected: 4
  -> Query 8/27: (ta="ds RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 1 results. Fetching yearly...
[INFO] Requested: 1-1 | Received: 1-1 | Total expected: 1
  -> Query 9/27: (ta="RNA interference" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2024: 142 results. Fetching yearly...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 142
[INFO] Requested: 91-142 | Received: 91-142 | Total expected: 142
  -> Query 10/27: (ta="interfering RNA" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...

           Patent_ID Family_ID Country
30      US11510939B1  84230742      US
9440  US2025263707A1  96740440      US
1836  US2022235354A1  72941017      US
1835  US2022362398A1  72941793      US
8164  US2025304968A1  97178118      US

In [3]:
# (Optional) Check your weekly data quota before running
print("Checking quota...")
epo_api_codes.check_epo_quota(CONSUMER_KEY, CONSUMER_SECRET)

# Run the extraction for the year 2022
print("\nStarting extraction...")
df_2022_2025_codes = epo_api_codes.download_patent_ids(
    consumer_key    = CONSUMER_KEY,
    consumer_secret = CONSUMER_SECRET,
    start_year      = 2022,
    end_year        = 2025,
    applicant_filter = None,    # Wildcard company name to narrow results.
                                # e.g. "Alnylam*" → only Alnylam patents
                                #      None       → all applicants

    only_applicant   = False,   # Controls what the query is built from:
                                # False → CPC/IPC codes + applicant filter (default)
                                # True  → applicant name only, codes are ignored
                                #         (use this for a full company portfolio)
)

# Display the first few rows of the extracted DataFrame
df_2022_2025_codes.head()

Checking quota...
=============================================
      EPO OPS API - STATUS DASHBOARD
=============================================

[DATA CONSUMPTION]
Weekly Volume Used: 4.4912% (179.65 MB / 4000 MB)
Quota Remaining:    95.5088%
Current API Load:   30 requests/minute

---------------------------------------------
[OK] Server clear. Safe to proceed with extraction.
---------------------------------------------

Starting extraction...

=== STARTING EPO ID EXTRACTION (2022 - 2025) ===
[INFO] 6 independent query conditions.
[INFO] Exclusions active: C12N15/115 (Aptamers), C12N15/117 (Immunomodulatory)

[INFO] Processing year 2022...
  -> Query 1/6: (cpc=/low "C12N15/11" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 8471 results (>2000). Slicing by month...
[INFO] Year 2022, month 1: fetching 1123 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1123
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1123
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1123
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1123
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1123
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1123
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1123
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1123
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1123
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1123
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1123
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1123
[INFO] Requested: 1081-1123 | Received: 1081-1123 | Total expected: 1123
[INFO] Year 2022, month 2: fetching 1046 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1046
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1046
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1046
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1046
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1046
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1046
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1046
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1046
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1046
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1046
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1046
[INFO] Requested: 991-1046 | Received: 991-1046 | Total expected: 1046
[INFO] Year 2022, month 3: fetching 1304 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1304
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1304
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1304
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1304
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1304
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1304
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1304
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1304
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1304
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1304
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1304
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1304
[INFO] Requested: 1081-1170 | Received: 1081-1170 | Total expected: 1304
[INFO] Requested: 1171-1260 | Received: 1171-1260 | Total expected: 1304
[INFO] Requested: 1261-1304 | Received: 1261-1304 | Total expected: 1304
[INFO] Year 2022, month 4: fetching 1028 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1028
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1028
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1028
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1028
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1028
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1028
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1028
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1028
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1028
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1028
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1028
[INFO] Requested: 991-1028 | Received: 991-1028 | Total expected: 1028
[INFO] Year 2022, month 5: fetching 1140 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1140
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1140
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1140
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1140
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1140
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1140
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1140
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1140
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1140
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1140
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1140
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1140
[INFO] Requested: 1081-1140 | Received: 1081-1140 | Total expected: 1140
[INFO] Year 2022, month 6: fetching 1199 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1199
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1199
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1199
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1199
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1199
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1199
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1199
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1199
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1199

[AUTH] Generating a new EPO access token...
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1199
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1199
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1199
[INFO] Requested: 1081-1170 | Received: 1081-1170 | Total expected: 1199
[INFO] Requested: 1171-1199 | Received: 1171-1199 | Total expected: 1199
[INFO] Year 2022, month 7: fetching 1161 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1161
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1161
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1161
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1161
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1161
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1161
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1161
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1161
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1161
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1161
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1161
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1161
[INFO] Requested: 1081-1161 | Received: 1081-1161 | Total expected: 1161
[INFO] Year 2022, month 8: fetching 1207 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1207
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1207
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1207
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1207
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1207
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1207
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1207
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1207
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1207
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1207
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1207
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1207
[INFO] Requested: 1081-1170 | Received: 1081-1170 | Total expected: 1207
[INFO] Requested: 1171-1207 | Received: 1171-1207 | Total expected: 1207
[INFO] Year 2022, month 9: fetching 1179 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1179
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1179
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1179
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1179
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1179
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1179
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1179
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1179
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1179
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1179
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1179
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1179
[INFO] Requested: 1081-1170 | Received: 1081-1170 | Total expected: 1179
[INFO] Requested: 1171-1179 | Received: 1171-1179 | Total expected: 1179
[INFO] Year 2022, month 10: fetching 1071 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1071
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1071
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1071
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1071
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1071
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1071
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1071
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1071
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1071
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1071
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1071
[INFO] Requested: 991-1071 | Received: 991-1071 | Total expected: 1071
[INFO] Year 2022, month 11: fetching 1091 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1091
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1091
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1091
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1091
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1091
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1091
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1091
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1091
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1091
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1091
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1091
[INFO] Requested: 991-1080 | Received: 991-1080 | Total expected: 1091
[INFO] Requested: 1081-1091 | Received: 1081-1091 | Total expected: 1091
[INFO] Year 2022, month 12: fetching 1078 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 1078
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 1078
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 1078
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 1078
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 1078
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 1078
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 1078
[INFO] Requested: 631-720 | Received: 631-720 | Total expected: 1078
[INFO] Requested: 721-810 | Received: 721-810 | Total expected: 1078
[INFO] Requested: 811-900 | Received: 811-900 | Total expected: 1078
[INFO] Requested: 901-990 | Received: 901-990 | Total expected: 1078
[INFO] Requested: 991-1078 | Received: 991-1078 | Total expected: 1078
  -> Query 2/6: (cpc=/low "A61K31/7088" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 3695 results (>2000). Slicing by month...
[INFO] Year 2022, month 1: fetching 484 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 484
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 484

[AUTH] Generating a new EPO access token...
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 484
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 484
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 484
[INFO] Requested: 451-484 | Received: 451-484 | Total expected: 484
[INFO] Year 2022, month 2: fetching 487 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 487
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 487
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 487
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 487
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 487
[INFO] Requested: 451-487 | Received: 451-487 | Total expected: 487
[INFO] Year 2022, month 3: fetching 616 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 616
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 616
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 616
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 616
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 616
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 616
[INFO] Requested: 541-616 | Received: 541-616 | Total expected: 616
[INFO] Year 2022, month 4: fetching 478 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 478
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 478
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 478
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 478
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 478
[INFO] Requested: 451-478 | Received: 451-478 | Total expected: 478
[INFO] Year 2022, month 5: fetching 500 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 500
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 500
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 500
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 500
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 500
[INFO] Requested: 451-500 | Received: 451-500 | Total expected: 500
[INFO] Year 2022, month 6: fetching 521 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 521
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 521
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 521
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 521
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 521
[INFO] Requested: 451-521 | Received: 451-521 | Total expected: 521
[INFO] Year 2022, month 7: fetching 530 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 530
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 530
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 530
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 530
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 530
[INFO] Requested: 451-530 | Received: 451-530 | Total expected: 530
[INFO] Year 2022, month 8: fetching 519 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 519
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 519
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 519
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 519
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 519
[INFO] Requested: 451-519 | Received: 451-519 | Total expected: 519
[INFO] Year 2022, month 9: fetching 505 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 505
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 505
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 505
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 505
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 505
[INFO] Requested: 451-505 | Received: 451-505 | Total expected: 505
[INFO] Year 2022, month 10: fetching 436 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 436
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 436
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 436
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 436
[INFO] Requested: 361-436 | Received: 361-436 | Total expected: 436
[INFO] Year 2022, month 11: fetching 497 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 497
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 497
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 497
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 497
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 497
[INFO] Requested: 451-497 | Received: 451-497 | Total expected: 497
[INFO] Year 2022, month 12: fetching 498 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 498
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 498
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 498
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 498
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 498
[INFO] Requested: 451-498 | Received: 451-498 | Total expected: 498
  -> Query 3/6: (ipc="C12N15/113" NOT (cpc="C12N15/115" OR cpc="C12N15/117"))...
[INFO] Year 2022: 5060 results (>2000). Slicing by month...
[INFO] Year 2022, month 1: fetching 530 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 530
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 530
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 530
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 530
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 530
[INFO] Requested: 451-530 | Received: 451-530 | Total expected: 530
[INFO] Year 2022, month 2: fetching 464 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 464
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 464
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 464
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 464
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 464
[INFO] Requested: 451-464 | Received: 451-464 | Total expected: 464
[INFO] Year 2022, month 3: fetching 633 results...

[AUTH] Generating a new EPO access token...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 633
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 633
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 633
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 633
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 633
[INFO] Requested: 451-540 | Received: 451-540 | Total expected: 633
[INFO] Requested: 541-630 | Received: 541-630 | Total expected: 633
[INFO] Requested: 631-633 | Received: 631-633 | Total expected: 633
[INFO] Year 2022, month 4: fetching 538 results...
[INFO] Requested: 1-90 | Received: 1-90 | Total expected: 538
[INFO] Requested: 91-180 | Received: 91-180 | Total expected: 538
[INFO] Requested: 181-270 | Received: 181-270 | Total expected: 538
[INFO] Requested: 271-360 | Received: 271-360 | Total expected: 538
[INFO] Requested: 361-450 | Received: 361-450 | Total expected: 538

            Patent_ID Family_ID Country
15829  US2022195406A1  72837592      US
15888  US2022265774A1  58794205      US
15928  US2022291216A1  27580991      US
15955  US2022370487A1  84028798      US
16036  US2023027209A1  84975970      US

X

In [ ]:
# =============================================================================
# PATENT FAMILY COMPARISON
# =============================================================================
# Make sure compare_patents.py is in the same folder as this notebook.
# The two CSV files must also be in the same folder (or provide full paths).
# =============================================================================

from compare_patents import compare

# Run the comparison.
# This will:
#   1. Load both CSV files
#   2. Normalise Family_IDs (strips leading zeros to avoid false mismatches)
#   3. Print a summary table in the cell output
#   4. Automatically save three CSVs to the current folder:
#        - patents_only_True_Alnylam.csv  → families exclusive to file A
#        - patents_only_terms_only.csv    → families exclusive to file B
#        - patents_in_common.csv          → families present in both files
#
# To skip saving (e.g. for a quick exploratory check), pass save=False:
#   only_a, only_b, shared = compare("a.csv", "b.csv", save=False)

only_a, only_b, shared = compare(
    "EPO_siRNA_IDs_2022_2025_only_applicant_Alnylam.csv",  # File A: Alnylam-filtered
    "EPO_siRNA_IDs_2022_2025_terms_only.csv",              # File B: terms-based
)

# -----------------------------------------------------------------------------
# The function returns three DataFrames you can explore directly in the notebook:
#   Example:
#   only_a  — families found ONLY in File A (Alnylam has them, terms_only doesn't)
#   only_b  — families found ONLY in File B (terms_only has them, Alnylam doesn't)
#   shared  — families found in BOTH files  (one row per family, source = File A)
#
# Each DataFrame has three columns: Patent_ID | Family_ID | Country
# -----------------------------------------------------------------------------

shared.head()
only_a.head()
only_b.head()

Loading files...

  PATENT FAMILY COMPARISON  (by Family_ID)

  File A — 2025_only_applicant_Alnylam:    317 rows  |    317 unique families
  File B — 2025_codes_only     : 68,205 rows  |  68,205 unique families

  Only in A  (2025_only_applicant_Alnylam) :     8 families  →      8 rows
  Only in B  (2025_codes_only) : 67,896 families  →  67,896 rows
  In both files              :   309 families  →    309 rows

  Total unique families      : 68,213


[SAVED]     8 rows  →  patentes_only_2025_only_applicant_Alnylam.csv
[SAVED] 67,896 rows  →  patentes_only_2025_codes_only.csv
[SAVED]   309 rows  →  patentes_in_commum_2025_only_applicant_Alnylam and 2025_codes_only.csv

        Patent_ID Family_ID Country
0  US2022195406A1  72837592      US
1  US2022265774A1  58794205      US
2  US2022291216A1  27580991      US
3  US2022370487A1  84028798      US
4  US2023027209A1  84975970      US

In [ ]:
from epo_api_Metadata import fetch_biblio_from_csv

df_metadata = fetch_biblio_from_csv(
    ids_csv         = "EPO_siRNA_IDs_2022_2025_terms_only.csv",
    consumer_key    = CONSUMER_KEY,
    consumer_secret = CONSUMER_SECRET,
)

df_metadata.head()

=== STARTING EPO METADATA FETCH ===
[INFO] Input file : EPO_siRNA_IDs_2022_2025_terms_only.csv
[INFO] Patent IDs : 9111
[INFO] Batches : 92 x 100 IDs per batch

[AUTH] Generating a new EPO access token...
[INFO] Batch 1 complete — 100 records fetched so far.
[INFO] Batch 2 complete — 200 records fetched so far.
[INFO] Batch 3 complete — 300 records fetched so far.
[INFO] Batch 4 complete — 400 records fetched so far.
[INFO] Batch 5 complete — 500 records fetched so far.
[INFO] Batch 6 complete — 600 records fetched so far.
[INFO] Batch 7 complete — 700 records fetched so far.
[INFO] Batch 8 complete — 800 records fetched so far.
[INFO] Batch 9 complete — 900 records fetched so far.
[INFO] Batch 10 complete — 1000 records fetched so far.
[INFO] Batch 11 complete — 1100 records fetched so far.
[INFO] Batch 12 complete — 1200 records fetched so far.
[INFO] Batch 13 complete — 1300 records fetched so far.
[INFO] Batch 14 complete — 1400 records fetched so far.
[INFO] Batch 15 complete — 1500 records fetched so far.
[INFO] Batch 16 complete — 1600 records fetched so far.
[INFO] Batch 17 complete — 1700 records fetched so far.
[INFO] Batch 18 complete — 1800 records fetched so far.
[INFO] Batch 19 complete — 1900 records fetched so far.
[INFO] Batch 20 complete — 2000 records fetched so far.
[INFO] Batch 21 complete — 2100 records fetched so far.
[INFO] Batch 22 complete — 2200 records fetched so far.
[INFO] Batch 23 complete — 2300 records fetched so far.
[INFO] Batch 24 complete — 2400 records fetched so far.
[INFO] Batch 25 complete — 2500 records fetched so far.
[INFO] Batch 26 complete — 2600 records fetched so far.
[INFO] Batch 27 complete — 2700 records fetched so far.

[AUTH] Generating a new EPO access token...
[INFO] Batch 28 complete — 2800 records fetched so far.
[INFO] Batch 29 complete — 2900 records fetched so far.
[INFO] Batch 30 complete — 3000 records fetched so far.
[INFO] Batch 31 complete — 3100 records fetched so far.
[INFO] Batch 32 complete — 3200 records fetched so far.
[INFO] Batch 33 complete — 3300 records fetched so far.
[INFO] Batch 34 complete — 3400 records fetched so far.
[INFO] Batch 35 complete — 3500 records fetched so far.
[INFO] Batch 36 complete — 3600 records fetched so far.
[INFO] Batch 37 complete — 3700 records fetched so far.
[INFO] Batch 38 complete — 3800 records fetched so far.
[INFO] Batch 39 complete — 3900 records fetched so far.
[INFO] Batch 40 complete — 4000 records fetched so far.
[INFO] Batch 41 complete — 4100 records fetched so far.
[INFO] Batch 42 complete — 4200 records fetched so far.
[INFO] Batch 43 complete — 4300 records fetched so far.
[INFO] Batch 44 complete — 4400 records fetched so far.
[INFO] Batch 45 complete — 4500 records fetched so far.
[INFO] Batch 46 complete — 4600 records fetched so far.
[INFO] Batch 47 complete — 4700 records fetched so far.
[INFO] Batch 48 complete — 4800 records fetched so far.
[INFO] Batch 49 complete — 4900 records fetched so far.
[INFO] Batch 50 complete — 5000 records fetched so far.
[INFO] Batch 51 complete — 5100 records fetched so far.
[INFO] Batch 52 complete — 5200 records fetched so far.
[INFO] Batch 53 complete — 5300 records fetched so far.
[INFO] Batch 54 complete — 5400 records fetched so far.
[INFO] Batch 55 complete — 5500 records fetched so far.
[INFO] Batch 56 complete — 5600 records fetched so far.
[INFO] Batch 57 complete — 5700 records fetched so far.
[INFO] Batch 58 complete — 5800 records fetched so far.
[INFO] Batch 59 complete — 5900 records fetched so far.
[INFO] Batch 60 complete — 6000 records fetched so far.
[INFO] Batch 61 complete — 6100 records fetched so far.
[INFO] Batch 62 complete — 6200 records fetched so far.
[INFO] Batch 63 complete — 6300 records fetched so far.
[INFO] Batch 64 complete — 6400 records fetched so far.
[INFO] Batch 65 complete — 6500 records fetched so far.
[INFO] Batch 66 complete — 6600 records fetched so far.
[INFO] Batch 67 complete — 6700 records fetched so far.
[INFO] Batch 68 complete — 6800 records fetched so far.
[INFO] Batch 69 complete — 6900 records fetched so far.
[INFO] Batch 70 complete — 7000 records fetched so far.
[INFO] Batch 71 complete — 7100 records fetched so far.
[INFO] Batch 72 complete — 7200 records fetched so far.
[INFO] Batch 73 complete — 7300 records fetched so far.
[INFO] Batch 74 complete — 7400 records fetched so far.
[INFO] Batch 75 complete — 7500 records fetched so far.
[INFO] Batch 76 complete — 7600 records fetched so far.
[INFO] Batch 77 complete — 7700 records fetched so far.
[INFO] Batch 78 complete — 7800 records fetched so far.
[INFO] Batch 79 complete — 7900 records fetched so far.
[INFO] Batch 80 complete — 8000 records fetched so far.
[INFO] Batch 81 complete — 8100 records fetched so far.
[INFO] Batch 82 complete — 8200 records fetched so far.
[INFO] Batch 83 complete — 8300 records fetched so far.

[AUTH] Generating a new EPO access token...
[INFO] Batch 84 complete — 8400 records fetched so far.
[INFO] Batch 85 complete — 8500 records fetched so far.
[INFO] Batch 86 complete — 8600 records fetched so far.
[INFO] Batch 87 complete — 8700 records fetched so far.
[INFO] Batch 88 complete — 8800 records fetched so far.
[INFO] Batch 89 complete — 8900 records fetched so far.
[INFO] Batch 90 complete — 9000 records fetched so far.
[INFO] Batch 91 complete — 9100 records fetched so far.
[INFO] Batch 92 complete — 9111 records fetched so far.

[SUCCESS] 9110 patents saved to: EPO_siRNA_IDs_2022_2025_terms_only_metadata.csv
[TIME] Fetch completed in 30m 29s

,Patent_ID,Country,Number,Kind,Family_ID,Priority_Date,Publication_Date,Applicant,Title,Abstract,IPCs,CPCs
1590,TW202200788A,TW,202200788,A,077928010,20220101,20220101,DIASORIN S P A [IT] | DIASORIN ITALIA S P A [IT],Assays for the detection of SARS-CoV-2,The present invention is directed to methods f...,,"C12Q1/70, C12Q1/701"
1602,TW202200163A,TW,202200163,A,075478225,20220101,20220101,DICERNA PHARMACEUTICALS INC [US],Compositions and methods for inhibiting ANGPTL...,Oligonucleotides are provided herein that inhi...,,"A61K31/713, A61K47/549, C12N15/113, C12N15/1136"
317,CN113881666A,CN,113881666,A,079011053,20220104,20220104,WEST CHINA HOSPITAL SICHUAN UNIV | 四川大学华西医院,SiRNA for interfering expression of p300 prote...,The invention relates to the field of nervous ...,,"A61K31/7088, A61P25/28, A61P3/10, C12N15/1137,..."
318,CN113881670A,CN,113881670,A,079007424,20220104,20220104,NANJING UNIVERSITY OF TECHNOLOGY | 南京师范大学,Construction method of transgenic plant capabl...,The invention provides a construction method o...,,"C12N15/1131, C12N15/8205, C12N15/8283"
378,CN113891939A,CN,113891939,A,073553862,20220104,20220104,SUZHOU RIBO BIOTECHNOLOGY CO LTD | 苏州瑞博生物技术股份有限公司,"NUCLEIC ACID, PHARMACEUTICAL COMPOSITION AND C...",Provided are an siRNA for inhibiting gene expr...,,"A61K31/713, A61K47/549, A61P9/10, C12N15/1137"